### ISSUE TITLE
net2axis.vh not checked in

### ISSUE THREAD

**Issue by philipaxer** [lucasbrasilino/net2axis#1]
Hi, 
it seems the header is missing (rework branch).

regards
Philip

**Comment by lucasbrasilino** [comment]
Hi,

Not sure what you mean. Couldn't see any reference to a `net2axis.sh` script. Can you elaborate?

Thanks!

**Comment by philipaxer** [comment]
Hi,

There is an include statement which cannot be resolved.

Regards
Philip

**Comment by philipaxer** [comment]
I.e here: ``include "net2axis.vh" `

**Comment by lucasbrasilino** [comment]
thanks for pointing it out! I've pushed the file.
